version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    binary: lanshare

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  draft: false
  prerelease: auto

brews:
  - name: lanshare
    repository:
      owner: sebaswvv
      name: homebrew-tap
    folder: Formula
    homepage: "https://github.com/sebaswvv/lan-share"
    description: "Share files instantly over your local network with QR codes"
    license: "MIT"

scoop:
  bucket:
    owner: sebaswvv
    name: scoop-bucket
  homepage: "https://github.com/sebaswvv/lan-share"
  description: "Share files instantly over your local network with QR codes"
  license: "MIT"
