version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    binary: lanshare

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  draft: false
  prerelease: auto

brews:
  - name: lanshare
    repository:
      owner: sebaswvv
      name: homebrew-tap
    directory: Formula
    homepage: "https://github.com/sebaswvv/lan-share"
    description: "Share files instantly over your local network with QR codes"
    license: "MIT"

scoops:
  - bucket:
      owner: sebaswvv
      name: scoop-bucket
    homepage: "https://github.com/sebaswvv/lan-share"
    description: "Share files instantly over your local network with QR codes"
    license: "MIT"
